In [1]:
!pip install tensorflow-gpu

  Using cached tensorboard-2.10.1-py3-none-any.whl (5.9 MB)
  Using cached keras-2.10.0-py2.py3-none-any.whl (1.7 MB)
  Using cached tensorflow_estimator-2.10.0-py2.py3-none-any.whl (438 kB)
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.11.0
    Uninstalling tensorflow-estimator-2.11.0:
      Successfully uninstalled tensorflow-estimator-2.11.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.11.0
    Uninstalling tensorboard-2.11.0:
      Successfully uninstalled tensorboard-2.11.0
  Attempting uninstall: keras
    Found existing installation: keras 2.11.0
    Uninstalling keras-2.11.0:
      Successfully uninstalled keras-2.11.0


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.11.0 requires keras<2.12,>=2.11.0, but you have keras 2.10.0 which is incompatible.
tensorflow-intel 2.11.0 requires tensorboard<2.12,>=2.11, but you have tensorboard 2.10.1 which is incompatible.
tensorflow-intel 2.11.0 requires tensorflow-estimator<2.12,>=2.11.0, but you have tensorflow-estimator 2.10.0 which is incompatible.


In [2]:
!pip install tensorflow

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-gpu 2.10.1 requires keras<2.11,>=2.10.0, but you have keras 2.11.0 which is incompatible.
tensorflow-gpu 2.10.1 requires tensorboard<2.11,>=2.10, but you have tensorboard 2.11.0 which is incompatible.


  Using cached tensorboard-2.11.0-py3-none-any.whl (6.0 MB)
  Using cached tensorflow_estimator-2.11.0-py2.py3-none-any.whl (439 kB)
  Using cached keras-2.11.0-py2.py3-none-any.whl (1.7 MB)
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.10.0
    Uninstalling tensorflow-estimator-2.10.0:
      Successfully uninstalled tensorflow-estimator-2.10.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.10.1
    Uninstalling tensorboard-2.10.1:
      Successfully uninstalled tensorboard-2.10.1
  Attempting uninstall: keras
    Found existing installation: keras 2.10.0
    Uninstalling keras-2.10.0:
      Successfully uninstalled keras-2.10.0


tensorflow-gpu 2.10.1 requires tensorflow-estimator<2.11,>=2.10.0, but you have tensorflow-estimator 2.11.0 which is incompatible.


In [3]:
!pip install keras 

In [4]:
!pip install numpy

In [5]:
!pip install pandas

In [6]:
import pandas as pd
import numpy as np

In [7]:
from keras.layers import Input, Conv2D, Lambda, Dense, Flatten,MaxPooling2D,Activation, Dropout                #merge
from keras.models import Model, Sequential
from keras.regularizers import l2
from keras import backend as K
from tensorflow.keras.optimizers import Adam
from skimage.io import imshow
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.layers import Embedding, LSTM, Dense, Dropout
np.random.seed(0)
from keras.preprocessing import sequence
from keras.initializers import glorot_uniform
np.random.seed(1)

In [8]:
with open('training.txt', 'r') as content:

  content1=content.read()
  file=content1.split("\n")
  print(len(file))

3521


In [9]:
i=0
file1=file[i].split(" ")
file1[0]

'PROMPT:'

In [10]:
i=0
maximum=0
j=0
z=[]
file2=[]
file3=[]
allfile1=[]
while i<3521:
  file1=file[i].split(" ")
  if file1[0]=="PROMPT:":
    if file2==[]:
      i+=1
      file2=[]
    else:
      i+=1
      file2.append("END")
      file3.append(file2)
      
      file2=[]
  else:
    for word in file1:
      if z==[]:
        z=word+" "
        allfile1.append(word)
      else:
        z=str(z)+word+" "
        
        allfile1.append(word)
    maximum=max(maximum,len(str(z)))
    file2.append(z)
    
    
    
    z=[]
    i+=1
print(maximum)
print(file3)

195
[['Blood is sent to the liver. ', 'The liver uses chemicals and proteins to treat the blood. ', 'The blood is cleaned. ', 'Energy is produced. ', 'The blood leaves the liver cleaned. ', ' ', 'END'], ['You wash the wound. ', 'You apply a bandaid or other covering if needed. ', 'The blood clots. ', 'A scab forms. ', 'The skin repairs itself under the protective cover of the scab. ', 'The scab falls off. ', ' ', 'END'], ['Get some seeds. ', 'Pick a spot to plant them. ', 'Dig a hole in the dirt. ', 'Put the seed in the hole. ', 'Pour some water on the seed and hold. ', 'Cover up the hole. ', 'Press down on it. ', 'Spray some plant food on it. ', ' ', 'END'], ['Blood delivers oxygen in the body. ', 'Proteins and acids are broken down in the liver. ', 'The liver releases waste in the form of urea. ', 'The blood carries the urea and carbon dioxide to the kidneys. ', 'The blood carries the urea and carbon dioxide to the kidneys. ', 'The kidneys strain the urea and salts needed from the bl

In [11]:
for i in allfile1:
  print(i)

Blood
is
sent
to
the
liver.
The
liver
uses
chemicals
and
proteins
to
treat
the
blood.
The
blood
is
cleaned.
Energy
is
produced.
The
blood
leaves
the
liver
cleaned.

You
wash
the
wound.
You
apply
a
bandaid
or
other
covering
if
needed.
The
blood
clots.
A
scab
forms.
The
skin
repairs
itself
under
the
protective
cover
of
the
scab.
The
scab
falls
off.

Get
some
seeds.
Pick
a
spot
to
plant
them.
Dig
a
hole
in
the
dirt.
Put
the
seed
in
the
hole.
Pour
some
water
on
the
seed
and
hold.
Cover
up
the
hole.
Press
down
on
it.
Spray
some
plant
food
on
it.

Blood
delivers
oxygen
in
the
body.
Proteins
and
acids
are
broken
down
in
the
liver.
The
liver
releases
waste
in
the
form
of
urea.
The
blood
carries
the
urea
and
carbon
dioxide
to
the
kidneys.
The
blood
carries
the
urea
and
carbon
dioxide
to
the
kidneys.
The
kidneys
strain
the
urea
and
salts
needed
from
the
blood.
The
carbon
dioxide
by
product
is
transported
back
to
the
lungs.
Carbon
dioxide
is
exhaled
by
the
lungs.

A
bird
lays
eggs
in
a
nest.
The


The
animal
has
entered
hibernation
mode.

Different
kinds
of
rocks
melt
into
magma.
Magma
cools
in
the
crust.
Magma
goes
to
the
surface
and
becomes
lava.
Lava
cools.
Cooled
magma
and
lava
become
igneous
rock.

The
farmer
chooses
a
crop
that
will
grow
well
in
his
region.
The
farmer
tills
the
soil
to
loosen
it.
The
farmer
spreads
seeds.
The
farmer
tills
again
to
plant
the
seeds.
Crops
grow.

Take
out
an
ice
cube
tray.
Fill
the
tray
with
water
from
the
faucet.
Put
the
ice
cube
tray
in
the
freezer.
Wait
for
several
hours.
The
water
will
freeze
and
become
ice.
Remove
the
ice
cube
tray
from
the
freezer.
Remove
the
ice
cubes
from
the
tray.

The
consumer
throws
aluminum
cans
and
foil
into
a
recycle
bin.
The
aluminum
is
collected.
Taken
to
a
treatment
plant.
The
aluminum
is
sorted
and
cleaned
ready
for
reprocessing.
The
aluminum
is
re-melted.
Turned
into
molten
aluminum.
The
aluminum
is
made
into
large
blocks
called
ingots.
The
ingots
are
sent
to
mills
to
be
rolled
out.
The
rolled
out
product
i

young
frog.
The
young
frog
continues
to
grow
to
adulthood.

The
flu
virus
has
receptors,
which
are
like
viral
Velcro,
on
the
surface
of
the
virus
particle.
The
receptors
will
lock
onto
a
target
cell
using
these
chemical
receptors
on
the
surface,
which
docks
onto
the
cell
surface.
The
receptors

then
go
into
the
cell.
The
receptors
use
it
like
a
factory.
The
receptors
take
it
over
and
make
it
produce
thousands
or
in
some
cases
millions
of
copies
of
new
viruses.
The
copies
come
streaming
out
of
the
cell.
The
copies
infect
other
cells
to
make
more
viruses,
or
they
escape
from
the
body
and
infect
a
new
victim.

Food
enters
the
body.
Food
begins
to
be
processed
by
the
digestive
system.
Food
begins
to
be
processed
by
the
digestive
system.
The
pancreas
releases
enzymes
to
aid
digestion.
Digested
food
affects
the
amount
of
sugar
in
the
blood.
The
pancreas
releases
one
hormone
to
lower
the
blood
sugar
(glucose)
level.
The
pancreas
releases
another
hormone
to
raisethe
blood
sugar
(glucose)
level

hypothalamus
in
the
brain
sends
a
message
to
the
body.
Sweat
glands
in
the
skin
receive
the
message.
The
sweat
glands
start
combining
water
and
chemicals
to
make
sweat.
The
sweat
leaves
the
skin
through
pores.

You
pack
up
your
car
with
food,
tents,
sleeping
bags,
etc.
You
pack
up
your
car
with
food,
tents,
sleeping
bags,
etc.
You
pack
up
your
car
with
food,
tents,
sleeping
bags,
etc.
Drive
to
your
camping
spot.
Put
up
your
tent.
Hide
your
food
from
bears.
Make
a
campfire.
Roast
marshmellows.
Go
to
sleep
in
the
tent.
Wake
up
and
enjoy
nature.

A
red
giant
burns
mass.
This
mass
creates
high
core
temperatures.
The
mass
decreases.
The
red
giant
can
no
longer
fuse
the
carbon
and
oxygen
in
its
center.
The
gravity
of
the
star
can
no
longer
hold
the
outside
layers.
The
layers
break
away.
Only
the
inner
core
remains.
This
inner
core
is
known
as
a
white
dwarf.

A
mine
is
excavated
in
the
side
of
a
mountain.
Miners
enter
the
mine.
Miners
remove
the
coal
from
the
mine.
The
coal
is
placed
into
car

energy.
Plants
absorb
carbon
dioxide
through
their
stoma.
Plants
absorb
water
through
their
roots
and
other
parts
of
themselves.
Plants
absorb
minerals
through
their
roots.
Plants
convert
these
inputs
into
sugars.
Sugars
can
be
used
as
energy
sources.
Oxygen
and
water
are
also
produced.
Excess
water
and
oxygen
are
released
through
stoma
and
other
parts
of
the
plant.

Acid
rain
enters
the
atmosphere
and
lands.
Acid
rain
enters
the
atmosphere
and
lands.
Makes
water
acidic.
Makes
water
acidic.
Kills
fish.
Kills
the
soils
in
trees.
Leaves
are
also
harmed.

Volcanos
contain
magma.
The
magma
is
very
hot.
The
magma
rises
toward
the
surface
of
the
volcano.
The
magma
cools.
The
magma
starts
to
harden
as
it
cools.
The
magma
is
sometimes
released
from
the
volcano
as
lava.
The
magma
or
lava
becomes
a
hard
rock
as
it
solidifies.

Networks
of
trees
start
forming.
The
trees
die
off.
The
dead
material
provides
nutrients
for
more
trees.
The
rising
trees
provide
shelter.
And
more
organisms
begin
to
thri

hot
air
and
blown
into
the
firebox
of
the
boiler.
Water
pumped
through
pipes
inside
the
boiler
is
turned
into
steam
by
the
heat.
The
pressure
of
the
steam
pushing
against
a
series
of
giant
blades
turns
the
turbine
shaft.
Turbine
shaft
is
connected
to
the
shaft
of
the
generator.
The
magnets
inside
the
generator
spin
within
wire
coils
to
produce
electricity.

Owls
hunt
around
their
hunting
territory
away
from
where
they
roost
during
the
day.
They
sit
still
on
a
perch,
like
a
stump
of
branch,
and
wait
for
prey.
They
use
their
highly
sensitive
hearing
to
locate
prey
that
cannot
be
seen.
They
use
their
very
keen
vision
to
see
prey
in
the
dark.
They
fly
silently,
without
flapping
their
wings,
in
order
to
surprise
the
prey.
The
owl
silently
glides
or
drops
on
its
prey,
grabbing
it
with
its
talons
and
beak.
The
owl
eats
the
prey,
or
carries
it
back
to
its
perch.

Air
is
brought
in
through
the
mouth.
Passes
through
the
lungs.
And
into
the
bronchial
tissue.
The
carbon
dioxide
is
removed.
The
lun

the
cracks
and
pores
in
the
rock
are
already
filled
with
water.
Rainwater
absorbs
some
carbon
dioxide
as
it
passes
through
the
atmosphere
and
even
more
as
it
drains
through
soil
and
decaying
vegetation.
The
water
combines
chemically
with
the
carbon
dioxide.
A
weak
carbonic
acid
solution
is
formed.
This
acid
slowly
dissolves
calcite,
forms
solution
cavities,
and
excavates
passageways.

An
animal
walk
s
by
a
plant.
The
animal
gets
seeds
stuck
in
their
fur.
The
animal
eats
some
fruit
of
the
tree
containing
seeds.
The
animal
loses
seeds
from
the
fur
in
other
locations.
Then
eaten
seeds
are
defecated
out
in
other
locations.

Place
the
water
in
a
pot.
Cover
the
pot
with
a
slightly
too
large
cover.
Place
a
larger
pot
under
the
first.
Heat
water
to
evaporation.
Water
vapor
will
collect
on
the
lid.
Drip
into
the
second
pot
as
fresh
water.
Salt
is
left
behind
in
the
original
pot.

Water
is
on
the
earth
in
oceans,
other
bodies
of
water,
and
living
creatures.
Water
evaporates
from
the
earth.
Water

In [41]:
tokenizer=Tokenizer()
def get_sequence_of_tokens(corpus):
    ## tokenization
    tokenizer.fit_on_texts(corpus)
    total_words = len(tokenizer.word_index)+ 1
    print(total_words)
    
    ## convert data to a token sequence 
    input_sequences = []
    for line in corpus:
        token_list = tokenizer.texts_to_sequences([line])[0]
        
        for i in range(1, len(token_list)):
            n_gram_sequence = token_list[:i+1]
            input_sequences.append(n_gram_sequence)
    return input_sequences, total_words

In [42]:
newFile1=[]
i=0
for sen in file3:
  newFile1.append(get_sequence_of_tokens(sen))
i=0
maximum=0
while i<390:
    maximum=max(maximum,newFile1[i][1])
    i+=1
    
print(maximum)

17
40
63
86
113
132
152
184
199
214
242
257
295
318
330
335
336
349
361
375
390
435
448
465
473
500
521
552
564
580
597
615
618
629
642
655
664
684
690
706
713
721
732
751
759
769
785
795
803
811
814
835
839
850
859
872
879
883
902
912
921
938
949
959
962
966
974
978
995
1008
1016
1031
1055
1068
1072
1077
1085
1115
1125
1133
1142
1144
1161
1167
1174
1183
1209
1217
1219
1224
1231
1239
1250
1256
1261
1271
1279
1314
1325
1330
1339
1351
1371
1377
1390
1391
1398
1409
1419
1427
1434
1436
1440
1441
1451
1452
1455
1458
1466
1468
1473
1498
1501
1513
1519
1529
1539
1560
1562
1566
1574
1580
1585
1586
1593
1604
1609
1613
1622
1626
1631
1639
1647
1652
1660
1665
1667
1668
1669
1680
1681
1685
1694
1696
1711
1716
1727
1731
1737
1746
1747
1754
1756
1768
1775
1779
1783
1798
1799
1801
1801
1807
1812
1827
1829
1835
1841
1852
1855
1864
1866
1867
1876
1879
1882
1887
1892
1896
1903
1915
1915
1920
1922
1924
1928
1930
1934
1940
1944
1945
1946
1954
1966
1973
1976
1977
1977
1992
1996
1999
2005
2008
2010
2015
201

In [14]:
maximum=3
newFile2=[]
i=0
while i<390:
  newFile2.append(newFile1[i][0])
  i+=1
print(newFile2[0])
i=0
while i<390:
  for q in newFile2[i]:
    maximum=min(maximum,len(q))
  i+=1
print(maximum)

[[2, 3], [2, 3, 7], [2, 3, 7, 5], [2, 3, 7, 5, 1], [2, 3, 7, 5, 1, 4], [1, 4], [1, 4, 8], [1, 4, 8, 9], [1, 4, 8, 9, 10], [1, 4, 8, 9, 10, 11], [1, 4, 8, 9, 10, 11, 5], [1, 4, 8, 9, 10, 11, 5, 12], [1, 4, 8, 9, 10, 11, 5, 12, 1], [1, 4, 8, 9, 10, 11, 5, 12, 1, 2], [1, 2], [1, 2, 3], [1, 2, 3, 6], [13, 3], [13, 3, 14], [1, 2], [1, 2, 15], [1, 2, 15, 1], [1, 2, 15, 1, 4], [1, 2, 15, 1, 4, 6]]
2


In [15]:
newFile2[0][0][0]

2

In [16]:
i=0

newFile3=[]
lst=[]
while i<390:
  z=len(newFile2[i])
  j=0
  while j<(z-1):
    k=len(newFile2[i][j])
    if((newFile2[i][j][0]==newFile2[i][j+1][0]) and (newFile2[i][j][1]==newFile2[i][j+1][1])):
      
      newFile3.append(newFile2[i][j])
       
    else:
      
      l=2
      lst=[]
      k=k-1
      while l>=0:
        
        lst.append(newFile2[i][j][k-l])
        l-=1
      l=0
      while (l<1):
        lst.append(newFile2[i][j+1][l])
        l+=1
      print
      newFile3.append(newFile2[i][j])
      newFile3.append(lst)
    j+=1
  i+=1
print(newFile3)
print(newFile2)


[[2, 3], [2, 3, 7], [2, 3, 7, 5], [2, 3, 7, 5, 1], [2, 3, 7, 5, 1, 4], [5, 1, 4, 1], [1, 4], [1, 4, 8], [1, 4, 8, 9], [1, 4, 8, 9, 10], [1, 4, 8, 9, 10, 11], [1, 4, 8, 9, 10, 11, 5], [1, 4, 8, 9, 10, 11, 5, 12], [1, 4, 8, 9, 10, 11, 5, 12, 1], [1, 4, 8, 9, 10, 11, 5, 12, 1, 2], [12, 1, 2, 1], [1, 2], [1, 2, 3], [1, 2, 3, 6], [2, 3, 6, 13], [13, 3], [13, 3, 14], [13, 3, 14, 1], [1, 2], [1, 2, 15], [1, 2, 15, 1], [1, 2, 15, 1, 4], [9, 20], [9, 20, 1], [9, 20, 1, 21], [20, 1, 21, 9], [9, 22], [9, 22, 10], [9, 22, 10, 23], [9, 22, 10, 23, 24], [9, 22, 10, 23, 24, 25], [9, 22, 10, 23, 24, 25, 26], [9, 22, 10, 23, 24, 25, 26, 27], [9, 22, 10, 23, 24, 25, 26, 27, 28], [26, 27, 28, 1], [1, 2], [1, 2, 29], [1, 2, 29, 10], [10, 5], [10, 5, 30], [10, 5, 30, 1], [1, 31], [1, 31, 32], [1, 31, 32, 33], [1, 31, 32, 33, 34], [1, 31, 32, 33, 34, 1], [1, 31, 32, 33, 34, 1, 35], [1, 31, 32, 33, 34, 1, 35, 36], [1, 31, 32, 33, 34, 1, 35, 36, 37], [1, 31, 32, 33, 34, 1, 35, 36, 37, 1], [1, 31, 32, 33, 34, 

In [17]:
def generate_padded_sequences(input_sequences):
    max_sequence_len =34                                               #max([len(x) for x in input_sequences])
    input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))
    
    predictors, label = input_sequences[:,:-1],input_sequences[:,-1]
    
    return predictors, label

In [18]:
x,y=generate_padded_sequences(newFile3)
i=0
while i<50:
  print(x[i],y[i])
  i+=1

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] 3
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 3] 7
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 3 7] 5
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 3 7 5] 1
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 3 7 5 1] 4
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 1 4] 1
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1] 4
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 4] 8
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 4 8] 9
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 4 8 9] 10
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  1  4  8  9 10] 11
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  1  4  8  9 10 11] 5
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  1  4  8  

In [51]:
def create_model(max_sequence_len, total_words):
    input_len = max_sequence_len - 1
    model = Sequential()
    # ----------Add Input Embedding Layer
    model.add(Embedding(total_words, 10, input_length=input_len))
    # ----------Add Hidden Layer 1 - LSTM Layer
    model.add(LSTM(100))
    model.add(Dropout(0.1))
    # ----------Add Output Layer
    model.add(Dense(total_words, activation='softmax'))
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')
    return model

In [52]:
max_sequence_len=34
total_words=2691
model = create_model(max_sequence_len, total_words)
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_8 (Embedding)     (None, 33, 10)            26910     
                                                                 
 lstm_8 (LSTM)               (None, 100)               44400     
                                                                 
 dropout_8 (Dropout)         (None, 100)               0         
                                                                 
 dense_8 (Dense)             (None, 2691)              271791    
                                                                 
Total params: 343,101
Trainable params: 343,101
Non-trainable params: 0
_________________________________________________________________


In [47]:
x=np.array(x)
y=np.array(y)

In [53]:
model.fit(x, y, epochs=200)

Epoch 1/200
639/639 [==============================] - 14s 17ms/step - loss: 6.1748
Epoch 2/200
639/639 [==============================] - 11s 17ms/step - loss: 5.9178
Epoch 3/200
639/639 [==============================] - 11s 17ms/step - loss: 5.8845
Epoch 4/200
639/639 [==============================] - 11s 17ms/step - loss: 5.8493
Epoch 5/200
639/639 [==============================] - 11s 17ms/step - loss: 5.7924
Epoch 6/200
639/639 [==============================] - 11s 17ms/step - loss: 5.7281
Epoch 7/200
639/639 [==============================] - 11s 17ms/step - loss: 5.6637
Epoch 8/200
639/639 [==============================] - 11s 17ms/step - loss: 5.5936
Epoch 9/200
639/639 [==============================] - 11s 17ms/step - loss: 5.5251
Epoch 10/200
639/639 [==============================] - 12s 19ms/step - loss: 5.4559
Epoch 11/200
639/639 [==============================] - 13s 20ms/step - loss: 5.3858
Epoch 12/200
639/639 [==============================] - 13s 20ms/step - lo

639/639 [==============================] - 14s 21ms/step - loss: 1.9848
Epoch 193/200
639/639 [==============================] - 14s 21ms/step - loss: 1.9778
Epoch 194/200
639/639 [==============================] - 14s 21ms/step - loss: 2.0003
Epoch 195/200
639/639 [==============================] - 14s 21ms/step - loss: 1.9630
Epoch 196/200
639/639 [==============================] - 14s 21ms/step - loss: 1.9618
Epoch 197/200
639/639 [==============================] - 14s 21ms/step - loss: 1.9640
Epoch 198/200
639/639 [==============================] - 14s 22ms/step - loss: 1.9659
Epoch 199/200
639/639 [==============================] - 14s 21ms/step - loss: 1.9566
Epoch 200/200
639/639 [==============================] - 14s 22ms/step - loss: 1.9523


In [62]:
def generate_text(seed_text, next_words, model):
    max_sequence_len=34
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list],maxlen=max_sequence_len-1, padding='pre')
        predicted = model.predict(token_list)
        prediction=np.argmax(predicted,axis=1)
        
        output_word = ""
        for word,index in tokenizer.word_index.items():
            if index == prediction:
                output_word = word
                break
        seed_text += " "+output_word
    return seed_text.title()


In [78]:
print (generate_text("Wood are", 20, model))

1/1 [==============================] - 0s 18ms/step
Wood Are The Into The Into Is Into The Into Is Into The Into Is Into The Into Is Into The Into


In [65]:
model.save("model_1.h5")

In [104]:
model1=Sequential([
                  
                  
                  tf.keras.layers.Embedding(2691,32, input_length=33),         #,input_length=9
                  tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128,return_sequences=True)),
                  tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
                  tf.keras.layers.Dropout(0.1),
                  tf.keras.layers.Dense(2691, activation='softmax'),



                  
])


In [105]:
model1.compile(loss='sparse_categorical_crossentropy', optimizer='adam')

In [106]:
model1.fit(x, y, epochs=200)

Epoch 1/200
639/639 [==============================] - 70s 95ms/step - loss: 6.1555
Epoch 2/200
639/639 [==============================] - 60s 94ms/step - loss: 5.8961
Epoch 3/200
639/639 [==============================] - 60s 93ms/step - loss: 5.8394
Epoch 4/200
639/639 [==============================] - 60s 93ms/step - loss: 5.7601
Epoch 5/200
639/639 [==============================] - 60s 93ms/step - loss: 5.6947
Epoch 6/200
639/639 [==============================] - 60s 93ms/step - loss: 5.6311
Epoch 7/200
639/639 [==============================] - 61s 95ms/step - loss: 5.5635
Epoch 8/200
639/639 [==============================] - 61s 95ms/step - loss: 5.4987
Epoch 9/200
639/639 [==============================] - 60s 94ms/step - loss: 5.4334
Epoch 10/200
639/639 [==============================] - 60s 94ms/step - loss: 5.3619
Epoch 11/200
639/639 [==============================] - 60s 94ms/step - loss: 5.2955
Epoch 12/200
639/639 [==============================] - 62s 96ms/step - lo

639/639 [==============================] - 91s 142ms/step - loss: 0.9085
Epoch 192/200
639/639 [==============================] - 92s 144ms/step - loss: 0.9218
Epoch 193/200
639/639 [==============================] - 92s 143ms/step - loss: 0.9490
Epoch 194/200
639/639 [==============================] - 93s 146ms/step - loss: 0.9267
Epoch 195/200
639/639 [==============================] - 92s 144ms/step - loss: 0.9249
Epoch 196/200
639/639 [==============================] - 93s 146ms/step - loss: 0.9144
Epoch 197/200
639/639 [==============================] - 94s 147ms/step - loss: 0.9194
Epoch 198/200
639/639 [==============================] - 93s 145ms/step - loss: 0.9316
Epoch 199/200
639/639 [==============================] - 94s 146ms/step - loss: 0.9328
Epoch 200/200
639/639 [==============================] - 97s 151ms/step - loss: 0.9336


In [82]:
def generate_text(seed_text, next_words, model):
    max_sequence_len=34
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list],maxlen=max_sequence_len-1, padding='pre')
        predicted = model.predict(token_list)
        prediction=np.argmax(predicted,axis=1)
        
        output_word = ""
        for word,index in tokenizer.word_index.items():
            if index == prediction:
                output_word = word
                break
        seed_text += " "+output_word
    return seed_text.title()

In [126]:
model1.save("model_3.h5")

In [127]:
print (generate_text(" evolution of",15, model1))

1/1 [==============================] - 0s 28ms/step
 Evolution Of The Rock Cell On Nutrients That Is Eventually It For Body Is Fill Very From


In [125]:
model.save_weights("paragraph.h5")

In [119]:
Air is breathable
Plant Grows

NameError: name 'Air' is not defined